import {useEffect,useMemo,useRef,useState} from 'react'
import VisualPreview from './VisualPreview'
import PlanPanel from './PlanPanel'
import AttachmentPicker from './AttachmentPicker'
import CodeWorkspace from './CodeWorkspace'
import BackendPanel from './BackendPanel'
import GitHubPanel from './GitHubPanel'
import PublishPanel from './PublishPanel'
import WorkspacePanel from './WorkspacePanel'

type Project={id:string;name:string;description:string;stack:string;status:string}
type AgentResponse={mode:string;steps:string[];message:string}
type ConversationMessage={id:string;projectId:string;role:'USER'|'ASSISTANT';mode:'BUILD'|'PLAN';content:string;createdAt:string}
type View='dashboard'|'builder'
type Filter='all'|'starred'|'owned'|'shared'
type StreamEvent={type:string;message?:string;result?:AgentResponse}
const suggestions=[['CRM workspace','Build a modern CRM dashboard with contacts, pipeline, tasks and analytics.'],['Booking app','Build a polished appointment booking app with availability, customers and reminders.'],['SaaS dashboard','Build a SaaS admin dashboard with authentication, subscriptions, usage and team management.'],['Internal tool','Build an internal operations tool with forms, approvals, audit history and role based access.']]

export default function App(){
 const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState<Project|null>(null),[view,setView]=useState<View>('dashboard'),[filter,setFilter]=useState<Filter>('all'),[prompt,setPrompt]=useState(''),[mode,setMode]=useState<'build'|'plan'>('build'),[busy,setBusy]=useState(false),[activity,setActivity]=useState<string[]>([]),[conversation,setConversation]=useState<ConversationMessage[]>([]),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState(''),[dashboardFiles,setDashboardFiles]=useState<File[]>([])
 const dashboardInputRef=useRef<HTMLInputElement|null>(null),abortRef=useRef<AbortController|null>(null),lastRequest=useRef<{project:Project;command:'plan'|'build';text:string}|null>(null)
 useEffect(()=>{void refreshProjects()},[]);useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true)}if(e.key==='Escape')setSearchOpen(false)};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[])
 async function refreshProjects(){const r=await fetch('/api/projects');if(r.ok)setProjects(await r.json())} async function refreshConversation(id:string){const r=await fetch(`/api/projects/${id}/conversation`);if(r.ok)setConversation(await r.json())}
 async function uploadAttachment(id:string,file:File){const form=new FormData();form.append('file',file);const r=await fetch(`/api/projects/${id}/attachments`,{method:'POST',body:form});if(!r.ok)throw new Error(`Unable to upload ${file.name}`)}
 async function execute(project:Project,command:'plan'|'build',text:string){const controller=new AbortController();abortRef.current=controller;lastRequest.current={project,command,text};setActivity([]);const r=await fetch(`/api/ai/${command}/stream`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/x-ndjson'},body:JSON.stringify({projectId:project.id,prompt:text}),signal:controller.signal});if(!r.ok||!r.body)throw new Error(`${command} command failed`);const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const {value,done}=await reader.read();buffer+=decoder.decode(value??new Uint8Array(),{stream:!done});const lines=buffer.split('\n');buffer=lines.pop()??'';for(const line of lines){if(!line.trim())continue;const event:StreamEvent=JSON.parse(line);if((event.type==='status'||event.type==='step')&&event.message)setActivity(c=>[...c,event.message!]);if(event.type==='result'&&event.result)setActivity(event.result.steps)}if(done)break}await refreshConversation(project.id)}
 async function createAndRun(){if(!prompt.trim())return;const initial=prompt.trim();setBusy(true);try{const r=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:projectName(initial),description:initial,stack:'React + Spring Boot + PostgreSQL'})});if(!r.ok)throw new Error('Unable to create project');const project:Project=await r.json();setSelected(project);setView('builder');setConversation([]);for(const file of dashboardFiles)await uploadAttachment(project.id,file);await execute(project,mode,initial);setPrompt('');setDashboardFiles([]);await refreshProjects()}catch(e){if((e as Error).name!=='AbortError')setActivity([(e as Error).message])}finally{setBusy(false);abortRef.current=null}}
 async function followUp(){if(!selected||!prompt.trim())return;const text=prompt.trim();setBusy(true);try{await execute(selected,mode,text);setPrompt('');await refreshProjects()}catch(e){if((e as Error).name!=='AbortError')setActivity([(e as Error).message])}finally{setBusy(false);abortRef.current=null}}
 async function retry(){const last=lastRequest.current;if(!last)return;setBusy(true);try{await execute(last.project,last.command,last.text)}finally{setBusy(false);abortRef.current=null}} function cancel(){abortRef.current?.abort();setBusy(false);setActivity(c=>['Request cancelled.',...c])}
 async function openProject(p:Project){setSelected(p);setView('builder');setPrompt('');setActivity([]);await refreshConversation(p.id)} function projectName(t:string){return t.trim().split(/\s+/).slice(0,5).join(' ')||'Untitled app'} const results=useMemo(()=>projects.filter(p=>`${p.name} ${p.description}`.toLowerCase().includes(query.toLowerCase())),[projects,query])
 if(view==='builder'&&selected)return <Builder project={selected} prompt={prompt} setPrompt={setPrompt} mode={mode} setMode={setMode} busy={busy} activity={activity} conversation={conversation} run={followUp} retry={retry} cancel={cancel} back={()=>setView('dashboard')}/>
 return <div className="creator-shell"><Sidebar filter={filter} setFilter={setFilter} search={()=>setSearchOpen(true)}/><main className="creator-main"><section className="hero"><div className="tool-pill">✦ &nbsp; Connect your tools &nbsp; →</div><h1>What will you build today?</h1><div className="hero-composer"><textarea autoFocus value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask ForgePilot to build an app…"/><input ref={dashboardInputRef} type="file" hidden multiple onChange={e=>setDashboardFiles(c=>[...c,...Array.from(e.target.files??[])])}/>{dashboardFiles.length>0&&<div className="dashboard-attachments">{dashboardFiles.map((f,i)=><span key={i}>{f.name}<button onClick={()=>setDashboardFiles(c=>c.filter((_,x)=>x!==i))}>×</button></span>)}</div>}<div className="composer-bottom"><button className="plus" onClick={()=>dashboardInputRef.current?.click()}>＋</button><div className="mode-switch"><button className={mode==='build'?'selected':''} onClick={()=>setMode('build')}>Build</button><button className={mode==='plan'?'selected':''} onClick={()=>setMode('plan')}>Plan</button></div><button className="send" disabled={!prompt.trim()||busy} onClick={()=>void createAndRun()}>{busy?'…':'↑'}</button></div></div><div className="suggestions">{suggestions.map(([a,b])=><button key={a} onClick={()=>setPrompt(b)}><b>{a}</b><span>{b}</span></button>)}</div></section><section className="projects-area"><div className="projects-head"><div><h2>Your projects</h2><p>Continue building or start from a fresh idea.</p></div></div>{projects.length===0?<div className="empty-projects"><b>No projects yet</b></div>:<div className="project-grid">{projects.map(p=><button className="project-card" key={p.id} onClick={()=>void openProject(p)}><div className="project-info"><b>{p.name}</b><span>{p.description||p.stack}</span><small>{p.status} · {p.stack}</small></div></button>)}</div>}</section></main>{searchOpen&&<div className="search-backdrop" onMouseDown={()=>setSearchOpen(false)}><div className="command" onMouseDown={e=>e.stopPropagation()}><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects…"/>{results.map(p=><button key={p.id} onClick={()=>{void openProject(p);setSearchOpen(false)}}><b>{p.name}</b></button>)}</div></div>}</div>
}
function Sidebar({filter,setFilter,search}:{filter:Filter;setFilter:(v:Filter)=>void;search:()=>void}){return <aside className="creator-sidebar"><div className="fp-mark">F</div><button className="workspace-switch"><span>F</span><b>ForgePilot Workspace</b><em>⌄</em></button><nav><button className="nav-active">⌂ <span>Dashboard</span></button><button onClick={search}>⌕ <span>Search</span><kbd>Ctrl K</kbd></button><button>◇ <span>Resources</span></button><button>⌘ <span>Connectors</span></button></nav><div className="nav-title">Projects</div><nav>{([['all','▦','All projects'],['starred','☆','Starred'],['owned','♙','Owned by me'],['shared','♧','Shared with me']] as [Filter,string,string][]).map(([k,i,l])=><button key={k} className={filter===k?'soft-active':''} onClick={()=>setFilter(k)}>{i} <span>{l}</span></button>)}</nav><div className="sidebar-spacer"/><div className="profile"><span>TS</span><div><b>Workspace</b><small>Owner</small></div></div></aside>}
function Builder({project,prompt,setPrompt,mode,setMode,busy,activity,conversation,run,retry,cancel,back}:{project:Project;prompt:string;setPrompt:(v:string)=>void;mode:'build'|'plan';setMode:(v:'build'|'plan')=>void;busy:boolean;activity:string[];conversation:ConversationMessage[];run:()=>void;retry:()=>void;cancel:()=>void;back:()=>void}){
 const [tab,setTab]=useState<'preview'|'code'|'backend'>('preview'),[viewport,setViewport]=useState<'desktop'|'tablet'|'mobile'>('desktop'),[refresh,setRefresh]=useState(0),[githubOpen,setGithubOpen]=useState(false),[publishOpen,setPublishOpen]=useState(false),[workspaceOpen,setWorkspaceOpen]=useState(false)
 useEffect(()=>{setRefresh(v=>v+1)},[conversation.length]);const previewUrl=`/api/projects/${project.id}/preview?v=${refresh}`
 return <div className="builder-shell"><header className="builder-top"><button onClick={back}>← Dashboard</button><b>{project.name}</b><div><button onClick={()=>setGithubOpen(true)}>GitHub</button><button onClick={()=>setWorkspaceOpen(true)}>Share</button><button className="publish" onClick={()=>setPublishOpen(true)}>Publish</button></div></header><aside className="builder-chat"><div className="chat-title"><b>ForgePilot</b><span>{mode==='build'?'Agent':'Plan'}</span></div><div className="chat-body">{conversation.map(m=><div key={m.id} className={m.role==='USER'?'user-prompt':'agent-message'}><small>{m.mode}</small>{m.content}</div>)}{mode==='plan'&&<PlanPanel projectId={project.id} onApproved={()=>setMode('build')}/>} {busy&&<div className="agent-message">ForgePilot is working… <button onClick={cancel}>Cancel</button></div>}{activity.length>0&&<div className="execution-steps">{activity.map((s,i)=><span key={i}>✓ {s}</span>)}</div>}</div><div className="builder-composer"><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask ForgePilot to make a change…"/><div><AttachmentPicker projectId={project.id}/><button onClick={()=>setMode(mode==='build'?'plan':'build')}>{mode==='build'?'Build':'Plan'}⌄</button><button disabled={busy} onClick={retry}>Retry</button><button className="send" disabled={busy||!prompt.trim()} onClick={run}>{busy?'…':'↑'}</button></div></div></aside><main className="live-preview"><div className="preview-top"><div><button className={tab==='preview'?'active':''} onClick={()=>setTab('preview')}>Preview</button><button className={tab==='code'?'active':''} onClick={()=>setTab('code')}>Code</button><button className={tab==='backend'?'active':''} onClick={()=>setTab('backend')}>Backend</button></div>{tab==='preview'&&<div><button onClick={()=>setViewport('desktop')}>Desktop</button><button onClick={()=>setViewport('tablet')}>Tablet</button><button onClick={()=>setViewport('mobile')}>Mobile</button><button onClick={()=>setRefresh(v=>v+1)}>↻</button><button onClick={()=>window.open(previewUrl,'_blank')}>↗</button></div>}</div>{tab==='preview'?<VisualPreview projectId={project.id} projectName={project.name} refresh={refresh} setRefresh={setRefresh} viewport={viewport} onTargetPrompt={t=>{setPrompt(t);setMode('build')}}/>:tab==='code'?<CodeWorkspace projectId={project.id} refreshToken={conversation.length} onPreviewChanged={()=>setRefresh(v=>v+1)}/>:<BackendPanel projectId={project.id}/>}</main>{githubOpen&&<GitHubPanel projectId={project.id} onClose={()=>setGithubOpen(false)}/>} {publishOpen&&<PublishPanel projectId={project.id} onClose={()=>setPublishOpen(false)}/>} {workspaceOpen&&<WorkspacePanel projectId={project.id} onClose={()=>setWorkspaceOpen(false)}/>}</div>
}
