import {useEffect,useState} from 'react'

type Backend={status:string;auth:{emailPassword:boolean;oauth:boolean;rbac:boolean};tables:{name:string;columns:{name:string;type:string;nullable:boolean}[];rowCount:number}[];secrets:Record<string,string>;logs:string[]}
type Generation={resourceName:string;packageName:string;files:Record<string,string>}
type AuthGeneration={packageName:string;roles:string[];oauthEnabled:boolean;emailPasswordEnabled:boolean;files:Record<string,string>}
type Props={projectId:string}

export default function BackendPanel({projectId}:Props){
  const [backend,setBackend]=useState<Backend|null>(null),[busy,setBusy]=useState(false),[secretName,setSecretName]=useState(''),[secretValue,setSecretValue]=useState(''),[tableName,setTableName]=useState('')
  const [resourceName,setResourceName]=useState('Customer'),[packageName,setPackageName]=useState('com.forgepilot.generated'),[generation,setGeneration]=useState<Generation|null>(null),[generating,setGenerating]=useState(false)
  const [authRoles,setAuthRoles]=useState('USER,ADMIN'),[authGeneration,setAuthGeneration]=useState<AuthGeneration|null>(null),[authGenerating,setAuthGenerating]=useState(false)
  useEffect(()=>{void load()},[projectId])
  async function load(){const r=await fetch(`/api/projects/${projectId}/backend`);if(r.ok)setBackend(await r.json())}
  async function provision(){setBusy(true);try{const r=await fetch(`/api/projects/${projectId}/backend/provision`,{method:'POST'});if(r.ok)setBackend(await r.json())}finally{setBusy(false)}}
  async function generate(){if(!resourceName.trim())return;setGenerating(true);try{const r=await fetch(`/api/projects/${projectId}/backend/generate`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({resourceName:resourceName.trim(),packageName:packageName.trim()})});if(!r.ok)throw new Error('Backend generation failed');setGeneration(await r.json());await load()}finally{setGenerating(false)}}
  async function generateAuth(){if(!backend)return;setAuthGenerating(true);try{const roles=authRoles.split(',').map(v=>v.trim()).filter(Boolean);const r=await fetch(`/api/projects/${projectId}/backend/auth/scaffold`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packageName:packageName.trim(),roles,emailPasswordEnabled:backend.auth.emailPassword,oauthEnabled:backend.auth.oauth})});if(!r.ok)throw new Error('Authentication generation failed');setAuthGeneration(await r.json());await load()}finally{setAuthGenerating(false)}}
  async function updateAuth(key:'emailPassword'|'oauth'|'rbac',value:boolean){if(!backend)return;const body={...backend.auth,[key]:value};const r=await fetch(`/api/projects/${projectId}/backend/auth`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.ok)setBackend(await r.json())}
  async function saveSecret(){if(!secretName.trim()||!secretValue)return;const r=await fetch(`/api/projects/${projectId}/backend/secrets`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:secretName.trim(),value:secretValue})});if(r.ok){setBackend(await r.json());setSecretName('');setSecretValue('')}}
  async function createTable(){const name=tableName.trim();if(!name)return;const r=await fetch(`/api/projects/${projectId}/backend/tables`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,columns:[{name:'id',type:'uuid primary key',nullable:false},{name:'created_at',type:'timestamp',nullable:false}]})});if(r.ok){setBackend(await r.json());setTableName('')}}
  if(!backend)return <div className="backend-panel"><p>Loading backend…</p></div>
  return <div className="backend-panel"><header><div><small>GENERATED BACKEND</small><h2>Data, authentication & Spring Boot code</h2></div><button disabled={busy} onClick={()=>void provision()}>{backend.status==='READY'?'Re-provision':'Provision backend'}</button></header><div className="backend-grid">
    <section className="backend-wide"><h3>Spring Boot generator</h3><p>Generate a real CRUD slice into this project workspace. ForgePilot creates the entity, repository, service, REST controller and generated datasource configuration.</p><div className="backend-inline"><input value={resourceName} onChange={e=>setResourceName(e.target.value)} placeholder="Customer"/><input value={packageName} onChange={e=>setPackageName(e.target.value)} placeholder="com.example.app"/><button disabled={generating||!resourceName.trim()} onClick={()=>void generate()}>{generating?'Generating…':'Generate backend code'}</button></div>{generation&&<div className="backend-generation"><b>{generation.resourceName}</b><span>{generation.packageName}</span>{Object.keys(generation.files).map(path=><code key={path}>{path}</code>)}</div>}</section>
    <section className="backend-wide"><h3>Authentication Builder</h3><p>Generate project-level auth scaffolding with roles, protected frontend routes, session helpers and Spring Security configuration.</p><div className="backend-inline"><input value={authRoles} onChange={e=>setAuthRoles(e.target.value)} placeholder="USER,ADMIN"/><button disabled={authGenerating} onClick={()=>void generateAuth()}>{authGenerating?'Generating…':'Generate auth scaffold'}</button></div>{authGeneration&&<div className="backend-generation"><b>Authentication scaffold ready</b><span>{authGeneration.roles.join(' · ')}</span>{Object.keys(authGeneration.files).map(path=><code key={path}>{path}</code>)}</div>}</section>
    <section><h3>Authentication</h3>{(['emailPassword','oauth','rbac'] as const).map(key=><label key={key}><input type="checkbox" checked={backend.auth[key]} onChange={e=>void updateAuth(key,e.target.checked)}/><span>{key==='emailPassword'?'Email & password':key==='oauth'?'OAuth providers':'Role-based access'}</span></label>)}</section><section><h3>Secrets</h3><div className="backend-inline"><input value={secretName} onChange={e=>setSecretName(e.target.value)} placeholder="API_KEY"/><input type="password" value={secretValue} onChange={e=>setSecretValue(e.target.value)} placeholder="value"/><button onClick={()=>void saveSecret()}>Save</button></div>{Object.entries(backend.secrets).map(([name,value])=><p key={name}><b>{name}</b><span>{value}</span></p>)}</section><section className="backend-wide"><h3>Database tables</h3><div className="backend-inline"><input value={tableName} onChange={e=>setTableName(e.target.value)} placeholder="customers"/><button onClick={()=>void createTable()}>Create starter table</button></div>{backend.tables.length===0?<p>No generated tables yet.</p>:backend.tables.map(table=><div className="backend-table" key={table.name}><b>{table.name}</b><span>{table.columns.map(c=>`${c.name}: ${c.type}`).join(' · ')}</span></div>)}</section><section className="backend-wide"><h3>Backend logs</h3><pre>{backend.logs.join('\n')||'No backend events yet.'}</pre></section></div></div>
}
