import {useEffect,useMemo,useState} from 'react'

type Catalog={id:string;name:string;category:string;authType:string;fields:string[]}
type Connection={connectorId:string;name:string;status:string;config:Record<string,string>}

const iconFor=(id:string)=>({stripe:'S',resend:'R','rest-api':'API',rest:'API',webhook:'↗',supabase:'S',slack:'#'}[id.toLowerCase()]||id.slice(0,2).toUpperCase())
const copyFor=(id:string)=>({stripe:'Accept payments and subscriptions.',resend:'Send transactional product email.','rest-api':'Connect any authenticated REST service.',rest:'Connect any authenticated REST service.',webhook:'Trigger external automations with webhooks.',supabase:'Connect hosted database and backend services.',slack:'Send project events to Slack.'}[id.toLowerCase()]||'Connect this service to your ForgePilot project.')

export default function ConnectorPanel({projectId}:{projectId:string}){
  const [catalog,setCatalog]=useState<Catalog[]>([]),[connections,setConnections]=useState<Connection[]>([]),[selected,setSelected]=useState<Catalog|null>(null),[config,setConfig]=useState<Record<string,string>>({}),[busy,setBusy]=useState(''),[query,setQuery]=useState('')
  useEffect(()=>{void load()},[projectId])
  async function load(){const [c,l]=await Promise.all([fetch('/api/connectors/catalog'),fetch(`/api/projects/${projectId}/connectors`)]);if(c.ok)setCatalog(await c.json());if(l.ok)setConnections(await l.json())}
  async function connect(){if(!selected)return;setBusy(selected.id);try{const r=await fetch(`/api/projects/${projectId}/connectors/${selected.id}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(config)});if(r.ok){setSelected(null);setConfig({});await load()}}finally{setBusy('')}}
  async function health(id:string){setBusy(id);try{await fetch(`/api/projects/${projectId}/connectors/${id}/health`,{method:'POST'});await load()}finally{setBusy('')}}
  async function disconnect(id:string){setBusy(id);try{await fetch(`/api/projects/${projectId}/connectors/${id}`,{method:'DELETE'});await load()}finally{setBusy('')}}
  const connected=(id:string)=>connections.find(c=>c.connectorId===id)
  const filtered=useMemo(()=>catalog.filter(item=>`${item.name} ${item.category}`.toLowerCase().includes(query.toLowerCase())),[catalog,query])
  return <div className="connector-surface">
    <div className="connector-hero"><div><span className="connector-eyebrow">INTEGRATIONS</span><h2>Connect your tools</h2><p>Bring payments, messaging, databases and external APIs into this ForgePilot project.</p></div><div className="connector-count">{connections.length} connected</div></div>
    <div className="connector-toolbar"><div className="connector-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search integrations"/></div><div className="connector-filter">All integrations</div></div>
    <div className="connector-grid">{filtered.map(item=>{const active=connected(item.id);return <article className="connector-card" key={item.id}><div className="connector-card-top"><div className={`connector-logo connector-logo-${item.id.toLowerCase().replace(/[^a-z0-9]/g,'')}`}>{iconFor(item.id)}</div><span className={`connector-status ${active?'is-connected':''}`}>{active?active.status:'Available'}</span></div><div className="connector-card-copy"><h3>{item.name}</h3><p>{copyFor(item.id)}</p><div className="connector-meta"><span>{item.category}</span><span>{item.authType}</span></div></div>{active?<div className="connector-actions"><button className="connector-secondary" disabled={!!busy} onClick={()=>void health(item.id)}>Check</button><button className="connector-danger" disabled={!!busy} onClick={()=>void disconnect(item.id)}>Disconnect</button></div>:<button className="connector-primary" disabled={!!busy} onClick={()=>{setSelected(item);setConfig({})}}>Connect</button>}</article>})}</div>
    {filtered.length===0&&<div className="connector-empty"><b>No integrations found</b><span>Try another search term.</span></div>}
    {selected&&<div className="connector-config-backdrop" onMouseDown={()=>setSelected(null)}><section className="connector-config" onMouseDown={e=>e.stopPropagation()}><div className="connector-config-head"><div className="connector-config-title"><div className="connector-logo">{iconFor(selected.id)}</div><div><small>CONNECT INTEGRATION</small><h3>{selected.name}</h3></div></div><button className="connector-close" aria-label="Close" onClick={()=>setSelected(null)}>×</button></div><p className="connector-config-desc">{copyFor(selected.id)} Credentials are stored securely and masked after save.</p><div className="connector-fields">{selected.fields.map(field=><label key={field}><span>{field.replaceAll('_',' ')}</span><input autoComplete="off" type={/key|secret|token|password/i.test(field)?'password':'text'} value={config[field]||''} onChange={e=>setConfig(current=>({...current,[field]:e.target.value}))} placeholder={`Enter ${field.replaceAll('_',' ').toLowerCase()}`}/></label>)}</div><div className="connector-config-actions"><button className="connector-secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="connector-primary" disabled={busy===selected.id||selected.fields.some(field=>!(config[field]||'').trim())} onClick={()=>void connect()}>{busy===selected.id?'Connecting…':'Connect integration'}</button></div></section></div>}
  </div>
}
