import {useEffect,useState} from 'react'

type Connection={owner:string;repo:string;branch:string;status:string;lastPushedAt?:string;lastPulledAt?:string}
type Status={configured:boolean;connection:Connection|null}
type Props={projectId:string;onClose:()=>void}

export default function GitHubPanel({projectId,onClose}:Props){
  const [status,setStatus]=useState<Status|null>(null),[owner,setOwner]=useState(''),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[busy,setBusy]=useState(''),[message,setMessage]=useState('')
  useEffect(()=>{void load()},[projectId])
  async function load(){const r=await fetch(`/api/projects/${projectId}/github`);if(r.ok){const data:Status=await r.json();setStatus(data);if(data.connection){setOwner(data.connection.owner);setRepo(data.connection.repo);setBranch(data.connection.branch)}}}
  async function connect(){setBusy('connect');setMessage('');try{const r=await fetch(`/api/projects/${projectId}/github/connect`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,repo,branch})});if(!r.ok)throw new Error('Unable to connect repository');await load();setMessage('Repository connected.')}catch(e){setMessage((e as Error).message)}finally{setBusy('')}}
  async function sync(direction:'push'|'pull'){setBusy(direction);setMessage('');try{const r=await fetch(`/api/projects/${projectId}/github/${direction}`,{method:'POST'});if(!r.ok)throw new Error(`${direction} failed`);const data=await r.json();setMessage(`${direction==='push'?'Pushed':'Pulled'} ${data.files?.length??0} files.`);await load()}catch(e){setMessage((e as Error).message)}finally{setBusy('')}}
  async function disconnect(){setBusy('disconnect');try{await fetch(`/api/projects/${projectId}/github`,{method:'DELETE'});setStatus(current=>current?{...current,connection:null}:current);setMessage('Repository disconnected.')}finally{setBusy('')}}
  return <div className="github-modal-backdrop" onMouseDown={onClose}><div className="github-panel" onMouseDown={e=>e.stopPropagation()}><header><div><small>CODE OWNERSHIP</small><h2>GitHub sync</h2></div><button onClick={onClose}>×</button></header>{status&&!status.configured&&<div className="github-warning">Server-side <b>GITHUB_TOKEN</b> is not configured. Connect metadata can be saved, but push/pull requires the token.</div>}<label>Owner<input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="organization-or-user"/></label><label>Repository<input value={repo} onChange={e=>setRepo(e.target.value)} placeholder="repository"/></label><label>Branch<input value={branch} onChange={e=>setBranch(e.target.value)} placeholder="main"/></label><div className="github-actions"><button disabled={!owner||!repo||!!busy} onClick={()=>void connect()}>{status?.connection?'Reconnect':'Connect'}</button>{status?.connection&&<><button disabled={!!busy||!status.configured} onClick={()=>void sync('pull')}>{busy==='pull'?'Pulling…':'Pull from GitHub'}</button><button className="primary" disabled={!!busy||!status.configured} onClick={()=>void sync('push')}>{busy==='push'?'Pushing…':'Push to GitHub'}</button></>}</div>{status?.connection&&<div className="github-status"><b>{status.connection.owner}/{status.connection.repo}</b><span>{status.connection.branch} · {status.connection.status}</span><small>Last push: {status.connection.lastPushedAt?new Date(status.connection.lastPushedAt).toLocaleString():'Never'}</small><small>Last pull: {status.connection.lastPulledAt?new Date(status.connection.lastPulledAt).toLocaleString():'Never'}</small><button disabled={!!busy} onClick={()=>void disconnect()}>Disconnect</button></div>}{message&&<p className="github-message">{message}</p>}</div></div>
}
