import {FormEvent,useState} from 'react'

export type LoginIdentity={email:string;name:string}

export default function LoginPage({onLogin}:{onLogin:(identity:LoginIdentity)=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('')
 function submit(e:FormEvent){e.preventDefault();if(!email.trim()||!password){setError('Enter your work email and password.');return}onLogin({email:email.trim(),name:email.trim().split('@')[0]||'User'})}
 function provider(name:string){setError(`${name} sign-in will use the enterprise identity provider when configured.`)}
 return <main className="login-shell"><section className="login-brand"><div className="login-logo">F</div><div><span className="login-eyebrow">FORGEPILOT AI</span><h1>Build production apps with your AI engineering team.</h1><p>Prompt, build, review, secure and publish from one governed workspace.</p></div><small>Internal AI application platform</small></section><section className="login-stage"><div className="login-card"><div className="login-card-logo">F</div><h2>Welcome to ForgePilot</h2><p>Sign in to continue to your workspace.</p><div className="login-providers"><button onClick={()=>provider('Google')}><b>G</b> Continue with Google</button><button onClick={()=>provider('GitHub')}><b>⌘</b> Continue with GitHub</button><button onClick={()=>provider('SSO')}><b>↗</b> Continue with SSO</button></div><div className="login-divider"><span>or</span></div><form onSubmit={submit}><label>Work email<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com"/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label><div className="login-options"><label><input type="checkbox"/> Remember me</label><button type="button">Forgot password?</button></div>{error&&<div className="login-error">{error}</div>}<button className="login-submit" type="submit">Sign in</button></form><p className="login-foot">Access is managed by your ForgePilot workspace administrator.</p></div></section></main>
}
