import {useEffect,useState} from 'react'
type Release={id:string;createdAt:string;visibility:string;status:string;published:boolean;publicPath:string;approvedBy?:string}
export default function PublishPanel({projectId,onClose}:{projectId:string;onClose:()=>void}){
 const [items,setItems]=useState<Release[]>([]),[visibility,setVisibility]=useState('WORKSPACE'),[message,setMessage]=useState('')
 async function load(){const r=await fetch(`/api/projects/${projectId}/publishes`);if(r.ok)setItems(await r.json())}
 useEffect(()=>{void load()},[projectId])
 async function request(){const r=await fetch(`/api/projects/${projectId}/publishes`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'workspace-owner',visibility})});if(r.ok){setMessage('Release snapshot created');await load()}}
 async function act(id:string,action:string){const r=await fetch(`/api/projects/${projectId}/publishes/${id}/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'workspace-owner'})});if(r.ok){setMessage(action==='publish'?'Published successfully':`${action} complete`);await load()}else setMessage(await r.text())}
 return <div className="modal-backdrop"><section className="side-panel"><header><div><b>Publish</b><small>Immutable releases, approvals and rollback</small></div><button onClick={onClose}>×</button></header><div className="panel-body"><label>Access<select value={visibility} onChange={e=>setVisibility(e.target.value)}><option>WORKSPACE</option><option>PUBLIC</option><option>PRIVATE</option></select></label><button className="primary" onClick={()=>void request()}>Create release</button>{message&&<p>{message}</p>}<h3>Release history</h3>{items.map(r=><article className="release-card" key={r.id}><div><b>{r.status}</b><small>{new Date(r.createdAt).toLocaleString()} · {r.visibility}</small></div><div>{r.status==='PENDING_APPROVAL'&&<><button onClick={()=>void act(r.id,'approve')}>Approve</button><button onClick={()=>void act(r.id,'reject')}>Reject</button></>}{r.status==='READY'&&<button className="primary" onClick={()=>void act(r.id,'publish')}>Publish</button>}{r.status==='PUBLISHED'&&<a href={r.publicPath} target="_blank">Open ↗</a>}{!r.published&&r.status!=='PENDING_APPROVAL'&&r.status!=='REJECTED'&&<button onClick={()=>void act(r.id,'rollback')}>Rollback</button>}</div></article>)}</div></section></div>
}
