type Props={slug:string;onAuthenticate:()=>void;onHome:()=>void}

type Page={eyebrow:string;title:string;summary:string;points:string[];cta:string;prompt:string}

const pages:Record<string,Page>={
  'solutions/engineering':{eyebrow:'Solutions · Engineering',title:'Move from requirement to verified implementation faster.',summary:'ForgePilot helps engineering teams plan changes, generate code, inspect diffs, run verification and preserve GitHub ownership.',points:['Plan mode for architecture and scope','Build mode with preview and verification','Code, version history and GitHub sync','Security checks before publish'],cta:'Build an engineering tool',prompt:'Build an engineering operations portal with service ownership, deployment status, incidents and audit history.'},
  'solutions/product':{eyebrow:'Solutions · Product',title:'Turn product intent into something teams can actually test.',summary:'Prototype flows, capture product requirements and iterate on a working application instead of stopping at static mockups.',points:['Prompt-to-project creation','Plan-first feature decomposition','Working preview for stakeholder review','Recoverable iterations and release history'],cta:'Prototype a product',prompt:'Build a product analytics dashboard with activation funnels, feature adoption, retention and experiment tracking.'},
  'solutions/founders':{eyebrow:'Solutions · Founders',title:'Validate the product, not just the pitch.',summary:'Go from idea to a real full-stack project while keeping the path to source ownership, integrations and deployment visible.',points:['Rapid prompt-first creation','Authentication and backend foundations','GitHub ownership path','Publish and deployment controls'],cta:'Build an MVP',prompt:'Build a SaaS MVP with sign in, subscription plans, customer dashboard, team invites and admin analytics.'},
  'solutions/operations':{eyebrow:'Solutions · Operations',title:'Replace spreadsheet workflows with governed internal apps.',summary:'Create operational tools with forms, approvals, integrations, audit trails and role-aware access.',points:['Internal workflows and approvals','Connectors and external APIs','Workspace roles','Audit and release evidence'],cta:'Build an operations tool',prompt:'Build an internal operations app with intake forms, approvals, SLA tracking, audit history and role-based dashboards.'},
  'solutions/websites':{eyebrow:'Solutions · Websites',title:'Create polished product surfaces backed by real engineering.',summary:'Use ForgePilot for responsive product sites and portals that can evolve into authenticated, integrated applications.',points:['Responsive starter experiences','Reusable design patterns','Live preview and iteration','Publish-ready project structure'],cta:'Build a website',prompt:'Build a responsive B2B product website with pricing, case studies, security, enterprise and contact sections.'},
  'solutions/internal-tools':{eyebrow:'Solutions · Internal tools',title:'Build tools that match how your teams actually work.',summary:'Generate role-aware dashboards and workflows, then connect them to APIs, data and company systems.',points:['Dashboards and data workflows','Role-aware workspace access','Connector framework','Versioned changes and rollback'],cta:'Build an internal tool',prompt:'Build an internal customer success workspace with accounts, health scores, renewal risk, tasks and notes.'},
  'resources/templates':{eyebrow:'Resources · Templates',title:'Start from proven application patterns.',summary:'Use ForgePilot starter prompts for common application categories, then customize structure, integrations and workflows with AI.',points:['CRM and pipeline apps','Booking and scheduling','SaaS admin dashboards','Internal operations tools'],cta:'Use a template',prompt:'Build a modern CRM dashboard with contacts, pipeline, tasks and analytics.'},
  'resources/connectors':{eyebrow:'Resources · Connectors',title:'Bring external systems into the build loop.',summary:'ForgePilot connector architecture supports project-scoped credentials, health checks and controlled external service access.',points:['API-key and OAuth-style connections','REST, webhook and GraphQL patterns','Connection health and diagnostics','Project-level isolation'],cta:'Build with connectors',prompt:'Build a customer operations app that connects email, billing and a REST CRM API with connection health status.'},
  'resources/docs':{eyebrow:'Resources · Documentation',title:'Understand the ForgePilot creator journey.',summary:'ForgePilot is organized around one path: prompt, plan, build, preview, validate, version, GitHub and deploy.',points:['Creator workflow concepts','Authentication and workspace model','Project generation lifecycle','Deployment and security gates'],cta:'Open ForgePilot',prompt:'Plan a production-ready internal application and explain the architecture before generating code.'},
  'resources/guides':{eyebrow:'Resources · Guides',title:'Build with production discipline from the first prompt.',summary:'Guides focus on useful implementation patterns: plan before changing code, validate outputs and keep source ownership recoverable.',points:['Prompt-writing patterns','Plan vs Build guidance','Preview and verification workflow','Security and deployment readiness'],cta:'Start guided build',prompt:'Plan and build a production-ready customer portal with authentication, account settings, support tickets and audit logging.'}
}

export function hasPublicPage(slug:string){return Boolean(pages[slug])}

export default function PublicContentPage({slug,onAuthenticate,onHome}:Props){
  const page=pages[slug]
  if(!page)return null
  function start(){sessionStorage.setItem('forgepilot.pendingPrompt',page.prompt);onAuthenticate()}
  return <main className="content-page">
    <button className="content-back" onClick={onHome}>← ForgePilot home</button>
    <section className="content-hero"><span>{page.eyebrow}</span><h1>{page.title}</h1><p>{page.summary}</p><button className="public-primary" onClick={start}>{page.cta} →</button></section>
    <section className="content-points">{page.points.map((point,index)=><article key={point}><b>{String(index+1).padStart(2,'0')}</b><h2>{point}</h2><p>Designed as part of the same ForgePilot project context rather than a disconnected workflow.</p></article>)}</section>
    <section className="content-cta"><div><span>Start from this use case</span><h2>Use the idea as a real ForgePilot project.</h2></div><button className="public-primary" onClick={start}>Start building →</button></section>
  </main>
}
