import {useEffect,useState} from 'react'
type Finding={id:string;rule:string;severity:string;file:string;message:string;recommendation:string;status:string}
type Scan={id:string;createdAt:string;depth:string;findings:Finding[];blocking:boolean;summary:string}
type Gate={allowed:boolean;message:string;scanId?:string}
type Trust={status:string;lastScan?:string;critical:number;high:number;medium:number;low:number;publishGatePassed:boolean;implementedControls:string[]}
type WorkspaceSummary={scannedProjects:number;blockedProjects:number;criticalFindings:number;highFindings:number;passingProjects:number}
export default function SecurityPanel({projectId,onClose,onFixPrompt}:{projectId:string;onClose:()=>void;onFixPrompt:(prompt:string)=>void}){
 const [scans,setScans]=useState<Scan[]>([]),[gate,setGate]=useState<Gate|null>(null),[trust,setTrust]=useState<Trust|null>(null),[workspace,setWorkspace]=useState<WorkspaceSummary|null>(null),[busy,setBusy]=useState(false),[depth,setDepth]=useState('BASIC')
 async function load(){const [s,g,t,w]=await Promise.all([fetch(`/api/projects/${projectId}/security/scans`),fetch(`/api/projects/${projectId}/security/gate`),fetch(`/api/projects/${projectId}/security/trust`),fetch('/api/workspace/security/summary')]);if(s.ok)setScans(await s.json());if(g.ok)setGate(await g.json());if(t.ok)setTrust(await t.json());if(w.ok)setWorkspace(await w.json())}
 useEffect(()=>{void load()},[projectId])
 async function scan(){setBusy(true);try{await fetch(`/api/projects/${projectId}/security/scan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({depth,actor:'workspace-owner'})});await load()}finally{setBusy(false)}}
 async function fix(finding:Finding){const r=await fetch(`/api/projects/${projectId}/security/findings/${finding.id}/suggest-fix`,{method:'POST'});if(r.ok){const data=await r.json();onFixPrompt(data.prompt);onClose()}}
 async function resolve(finding:Finding){await fetch(`/api/projects/${projectId}/security/findings/${finding.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'workspace-owner'})});await load()}
 const latest=scans[0]
 return <div className="modal-backdrop"><section className="side-panel security-panel"><header><div><b>Security Center</b><small>Scan, verify, remediate and enforce publish safety</small></div><button onClick={onClose}>×</button></header><div className="panel-body"><div className={`security-gate ${gate?.allowed?'pass':'block'}`}><b>{gate?.allowed?'✓ Publish gate passed':'⚠ Security attention required'}</b><span>{gate?.message??'Run a scan to evaluate this project.'}</span></div>{trust&&<div className="trust-grid"><div><small>Trust status</small><b>{trust.status}</b></div><div><small>Critical / High</small><b>{trust.critical} / {trust.high}</b></div><div><small>Medium / Low</small><b>{trust.medium} / {trust.low}</b></div><div><small>Publish</small><b>{trust.publishGatePassed?'Allowed':'Blocked'}</b></div></div>}{workspace&&<div className="workspace-security-summary"><b>Workspace security</b><span>{workspace.scannedProjects} scanned · {workspace.passingProjects} passing · {workspace.blockedProjects} blocked</span><small>{workspace.criticalFindings} critical · {workspace.highFindings} high findings</small></div>}<div className="security-actions"><select value={depth} onChange={e=>setDepth(e.target.value)}><option>BASIC</option><option>DEEP</option></select><button className="primary" disabled={busy} onClick={()=>void scan()}>{busy?'Scanning…':'Run security scan'}</button></div>{latest&&<><div className="security-summary"><b>{latest.summary}</b><small>{latest.depth} · {new Date(latest.createdAt).toLocaleString()}</small></div>{latest.findings.length===0?<div className="security-empty">No findings detected in the current workspace.</div>:latest.findings.map(f=><article className={`finding-card ${f.status==='RESOLVED'?'resolved':''}`} key={f.id}><div className="finding-head"><span className={`severity ${f.severity.toLowerCase()}`}>{f.severity}</span><b>{f.rule}</b><em>{f.status}</em></div><code>{f.file}</code><p>{f.message}</p><small>{f.recommendation}</small><div className="finding-actions"><button onClick={()=>void fix(f)}>Fix with AI</button>{f.status==='OPEN'&&<button onClick={()=>void resolve(f)}>Mark resolved</button>}</div></article>)}</>} {trust&&<><h3>Implemented controls</h3><div className="trust-controls">{trust.implementedControls.map(x=><span key={x}>✓ {x}</span>)}</div></>}<h3>Scan history</h3>{scans.map(s=><div className="scan-row" key={s.id}><span>{s.depth}</span><b>{s.summary}</b><small>{new Date(s.createdAt).toLocaleString()}</small></div>)}</div></section></div>
}
