import {useEffect,useState} from 'react'
type Finding={id:string;rule:string;severity:string;file:string;message:string;recommendation:string;status:string}
type Scan={id:string;createdAt:string;depth:string;findings:Finding[];blocking:boolean;summary:string}
type Gate={allowed:boolean;message:string;scanId?:string}
export default function SecurityPanel({projectId,onClose,onFixPrompt}:{projectId:string;onClose:()=>void;onFixPrompt:(prompt:string)=>void}){
 const [scans,setScans]=useState<Scan[]>([]),[gate,setGate]=useState<Gate|null>(null),[busy,setBusy]=useState(false),[depth,setDepth]=useState('BASIC')
 async function load(){const [s,g]=await Promise.all([fetch(`/api/projects/${projectId}/security/scans`),fetch(`/api/projects/${projectId}/security/gate`)]);if(s.ok)setScans(await s.json());if(g.ok)setGate(await g.json())}
 useEffect(()=>{void load()},[projectId])
 async function scan(){setBusy(true);try{await fetch(`/api/projects/${projectId}/security/scan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({depth,actor:'workspace-owner'})});await load()}finally{setBusy(false)}}
 async function fix(finding:Finding){const r=await fetch(`/api/projects/${projectId}/security/findings/${finding.id}/suggest-fix`,{method:'POST'});if(r.ok){const data=await r.json();onFixPrompt(data.prompt);onClose()}}
 const latest=scans[0]
 return <div className="modal-backdrop"><section className="side-panel security-panel"><header><div><b>Security</b><small>Scan generated app and enforce publish safety</small></div><button onClick={onClose}>×</button></header><div className="panel-body"><div className={`security-gate ${gate?.allowed?'pass':'block'}`}><b>{gate?.allowed?'✓ Publish gate passed':'⚠ Security attention required'}</b><span>{gate?.message??'Run a scan to evaluate this project.'}</span></div><div className="security-actions"><select value={depth} onChange={e=>setDepth(e.target.value)}><option>BASIC</option><option>DEEP</option></select><button className="primary" disabled={busy} onClick={()=>void scan()}>{busy?'Scanning…':'Run security scan'}</button></div>{latest&&<><div className="security-summary"><b>{latest.summary}</b><small>{latest.depth} · {new Date(latest.createdAt).toLocaleString()}</small></div>{latest.findings.length===0?<div className="security-empty">No findings detected in the current workspace.</div>:latest.findings.map(f=><article className="finding-card" key={f.id}><div className="finding-head"><span className={`severity ${f.severity.toLowerCase()}`}>{f.severity}</span><b>{f.rule}</b></div><code>{f.file}</code><p>{f.message}</p><small>{f.recommendation}</small><button onClick={()=>void fix(f)}>Fix with AI</button></article>)}</>}<h3>Scan history</h3>{scans.map(s=><div className="scan-row" key={s.id}><span>{s.depth}</span><b>{s.summary}</b><small>{new Date(s.createdAt).toLocaleString()}</small></div>)}</div></section></div>
}
