import {useEffect,useState} from 'react'
type Member={id:string;email:string;role:string;status:string};type Activity={id:string;at:string;actor:string;action:string;target:string}
export default function WorkspacePanel({projectId,onClose}:{projectId:string;onClose:()=>void}){
 const [members,setMembers]=useState<Member[]>([]),[activity,setActivity]=useState<Activity[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState('EDITOR'),[tab,setTab]=useState<'members'|'activity'>('members')
 async function load(){const r=await fetch('/api/workspace/collaboration');if(r.ok){const s=await r.json();setMembers(s.members??[]);setActivity(s.activity??[])}}
 useEffect(()=>{void load()},[])
 async function invite(){if(!email.trim())return;await fetch('/api/workspace/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,role,actor:'workspace-owner'})});setEmail('');await load()}
 async function share(){if(!email.trim())return;await fetch(`/api/workspace/projects/${projectId}/share`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,role,actor:'workspace-owner'})});await invite()}
 return <div className="modal-backdrop"><section className="side-panel"><header><div><b>Workspace</b><small>Members, project access and activity</small></div><button onClick={onClose}>×</button></header><div className="panel-tabs"><button className={tab==='members'?'active':''} onClick={()=>setTab('members')}>Members</button><button className={tab==='activity'?'active':''} onClick={()=>setTab('activity')}>Activity</button></div><div className="panel-body">{tab==='members'?<><div className="invite-row"><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="teammate@company.com"/><select value={role} onChange={e=>setRole(e.target.value)}>{['OWNER','ADMIN','EDITOR','VIEWER','APPROVER','PUBLISHER'].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>void invite()}>Invite</button><button className="primary" onClick={()=>void share()}>Share project</button></div>{members.map(m=><article className="member-row" key={m.id}><div><b>{m.email}</b><small>{m.status}</small></div><span>{m.role}</span></article>)}</>:activity.map(a=><article className="member-row" key={a.id}><div><b>{a.action}</b><small>{a.actor} · {new Date(a.at).toLocaleString()}</small></div><span>{a.target}</span></article>)}</div></section></div>
}
